{"name": "Ошибка при непрравильно указанном поле password", "status": "passed", "steps": [{"name": "Авторизация курьера", "status": "passed", "parameters": [{"name": "payload", "value": "{'login': 'xxwccbjktjaqudiabctbvlutgsflfnaleerxgzyykibgzerludzkktxoooxlnigzpflitusktyistmyjsrebsesxdebmrbfibyff', 'password': 'неверный логин/пароль'}"}], "start": 1734302229899, "stop": 1734302230071}], "parameters": [{"name": "invalid_data_fields", "value": "'password'"}], "start": 1734302229899, "stop": 1734302230072, "uuid": "9f2b0a43-49f1-4fc3-9563-dcaf1e90ac0a", "historyId": "ac98430753fdda3aad973f61a73e8635", "testCaseId": "5e7a8ed2e7ddfa7c8c95b1ddf06c09cf", "fullName": "tests.test_login_courier.TestLoginCourier#test_invalid_data_login_courier_error_not_found", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "i113855765"}, {"name": "thread", "value": "38750-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}